apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Marvin
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: marvin
  links:
    - url: https://github.com/noh4nsen/teste-backstage/tree/master/
      title: Repositorio
      icon: dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
