version: '3.5'
services:
  atm-marvin-webapp:
    image: atm-marvin-webapp
    container_name: marvin
    restart: always
    ports:
      - 80:80  
    build:
      context: .
      dockerfile: ./Dockerfile
    networks: 
      - postgres-net
      
networks:
    postgres-net:
        driver: bridge
        external: true
        name: postgres-net      